version: "3.1"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /opt/docker/projects/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: db0
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: root
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user
    restart: always