version: "3.1"
services:
  sonarqube:
    image: sonarqube:7.1
    ports:
      - "9000:9000"
    depends_on:
      - sonar-postgres
    volumes:
      - /opt/docker/projects/sonarqube/data:/opt/sonarqube/data
      - /opt/docker/projects/sonarqube/logs:/opt/sonarqube/logs
      - /opt/docker/projects/sonarqube/extensions:/opt/sonarqube/extensions
      - /opt/docker/projects/sonarqube/conf:/opt/sonarqube/conf
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonar-postgres/sonar
    restart: always
  sonar-postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker/projects/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    restart: always