version: "3.1"
services:
  droppy:
    image: silverwind/droppy
    ports:
      - "8989:8989"
    volumes:
      - ~/docker/volumes/droppy/config:/config
      - ~/docker/volumes/droppy/files:/files
    restart: always