version: "3.1"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always